# Docker compose file to run the following:
# - rabbitmq
# - minio
# - react frontend
# - database (mysql/postgres) (https://onexlab-io.medium.com/docker-compose-mysql-database-seed-3bcbdfc51e8b)
# - redis cache?
# - atomic microservices
# - complex microservices

version: "3"
services:
  mysql:
    container_name: esd_database
    build: ./backend/database
    ports:
      - 3308:3306
    env_file:
      - .env
    networks:
      - mynet

  atomic_service:
    container_name: sm_atomic_service
    build: ./backend/apis/tweets
    ports:
      - 5100:5100
    env_file:
      - ./backend/apis/tweets/.env
    networks:
      - mynet
    depends_on:
      - mysql

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./backend/bucket/minio/data:/data
    command: server /data --console-address ":9001"

networks:
  mynet:
    driver: bridge
