# Docker compose file to run the following:
# - rabbitmq
# - minio
# - react frontend
# - database (mysql/postgres) (https://onexlab-io.medium.com/docker-compose-mysql-database-seed-3bcbdfc51e8b)
# - redis cache?
# - atomic microservices
# - complex microservices

